### ISSUE TITLE
How to play the game

### ISSUE THREAD

**Issue by Skulp55** [main-thing/pizza-tower-android#1]
I don't know how to play:there is an apk somewere or i have to compile it myself

**Comment by Arthurmagno2013** [comment]
Hi

**Comment by Skulp55** [comment]
hi

Il giorno sab 18 nov 2023 alle ore 11:29 Arthurmagno2013 <
***@***.***> ha scritto:

**Comment by Skulp55** [comment]
so?

**Comment by Skulp55** [comment]
no apk?

**Comment by clunsdy315** [comment]
please give me link

**Comment by Skulp55** [comment]
I don't have an apk i'm not a dev

Il Ven 1 Dic 2023, 02:41 clunsdy315 ***@***.***> ha scritto:

**Comment by main-thing** [comment]
This is just the source code for the game. You can find the apk available [here](https://www.youtube.com/channel/UClMMptxlwlvI0wsSiZQAaFA).
